### ISSUE TITLE
Flyway config doesn't take effect

### ISSUE THREAD

**Issue by SpencerMichaels** [hi-ogawa/docker-flyway#4]
I'm running docker 1.12.0 with the current version of `docker-flyway`. As far as I know, everything is set up correctly, with the `flyway.conf` setting `flyway.url`, `flyway.user`, and `flyway.password`. However, the debug output for flyway, as given by `docker-compose run --rm flyway info -X`, shows:

```
Flyway 4.0.1 by Boxfuse

DEBUG: Java 1.7.0_101 (Oracle Corporation)
DEBUG: Linux 4.4.15-moby amd64

DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /root/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /flyway/jars
DEBUG: flyway.password ->
DEBUG: flyway.url ->
DEBUG: flyway.user ->
DEBUG: flyway.locations -> filesystem:/flyway/sql
DEBUG: Adding location to classpath: /flyway/drivers/h2-1.4.191.jar
DEBUG: Adding location to classpath: /flyway/drivers/mariadb-java-client-1.3.6.jar
DEBUG: Adding location to classpath: /flyway/drivers/hsqldb-2.3.3.jar
DEBUG: Adding location to classpath: /flyway/drivers/postgresql-9.4.1208.jre6.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbyclient-10.12.1.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/derby-10.12.1.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/sqlite-jdbc-3.7.15-M1.jar
DEBUG: Adding location to classpath: /flyway/drivers/jtds-1.3.1.jar
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
        at org.flywaydb.core.Flyway.execute(Flyway.java:1315)
        at org.flywaydb.core.Flyway.info(Flyway.java:1032)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:143)
        at org.flywaydb.commandline.Main.main(Main.java:102)
```

It seem that even though the config file is being read, but for whatever reason its contents don't take effect. Other Docker images of Flyway _do_ read the config, so I'm quite sure I didn't write it incorrectly — I think this is an issue with this image.

**Comment by hi-ogawa** [comment]
Hi @sxmichaels, thanks for the comment.
I didn't even know that there's an option `-X` for debug info.

Regarding this problem, I think this is because you didn't provide config file at `/flyway/flyway.conf`.
Please look at the example output from CI from here https://github.com/hi-ogawa/docker-flyway/pull/5#issuecomment-239665589
I hope this helps you.

**Comment by SpencerMichaels** [comment]
I've tried putting the config in all of those locations and still Flyway doesn't seem to read it. I set up [my own version](https://github.com/sxmichaels/docker-flyway) of a Docker image, based on yours with Flyway 4.0.3 instead and it does work; our images do nearly the same thing, so I suspect it might be an issue with v4.0.1.

**Comment by hi-ogawa** [comment]
Could you show me your `docker-compose.yml` file?
In [my example](https://github.com/hi-ogawa/docker-flyway/blob/a6396250ee041fc63e9a73d6011fd2caaa0d99c7/test/docker-compose.yml#L8), flyway container mounts host file `./flyway.conf` onto `/flyway/flyway.conf`.

**Comment by hi-ogawa** [comment]
@sxmichaels I think I found a problem. The image tag `hiogawa/flyway:latest` wasn't updated to current git repository master.
I'm sorry for your trouble, this is totally my bad.
I think it will be solved if you pull `hiogawa/flyway:latest` image again.
